Handling Image handler
KillerCodeMonkey/stencil-quill pull request #203
Opened 2022-06-03 13:15 UTC by hemanthkatam

Handling images with quill-image-uploader. 

with this it will add images in url format.

2022-06-03 15:37 UTC, KillerCodeMonkey requested changes

2022-06-03 15:37 UTC, KillerCodeMonkey commented on src/index.html
> +    <script src="https://cdn.quilljs.com/1.3.6/quill.min.js"></script>
quill is already added one line above

2022-06-03 15:37 UTC, KillerCodeMonkey commented on src/index.html
remove unnecessary new lines

2022-06-03 15:37 UTC, KillerCodeMonkey commented on src/index.html
> +  <link href="https://unpkg.com/quill-image-uploader@1.2.1/dist/quill.imageUploader.min.css" rel="stylesheet" />
fix indention

2022-06-04 17:51 UTC, hemanthkatam commented on src/index.html
> +    <script src="https://cdn.quilljs.com/1.3.6/quill.min.js"></script>
resolved

2022-06-04 17:51 UTC, hemanthkatam commented on src/index.html
> +  <link href="https://unpkg.com/quill-image-uploader@1.2.1/dist/quill.imageUploader.min.css" rel="stylesheet" />
resolved

2022-06-04 17:51 UTC, hemanthkatam commented on src/index.html
resolved

2022-06-07 10:58 UTC, hemanthkatam reviewed
resolved

2023-04-15 08:53 UTC, merged